### PR TITLE
Fix padding issue

### LINKED ISSUE #90: Help With Tweaking The Default Minimal Mistakes Layout
### tools: 
Chrome Version 113.0.5672.93 (Official Build) (64-bit)
VS Code
blog-in-a-box based project with no significant changes, only typical customization of _config.yaml and the below added files for stylesheets

existing: 
image

desired:
image

I was able to achieve the above using the modification to the css pictured in the 'desired' image. the new portion added to the .archive class was `padding 0 3rem !important;` 

## what I've tried so far: 
reading through this guide https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/ and attempting to follow the instructions under "Customizing" section. I tried creating a copy of main.scss first and then saw this note:

```
*Note*: To make more extensive changes and customize the Sass partials bundled in the gem. You will need to copy the complete contents of the _sass directory to <your_project> due to the way Jekyll currently reads those files.
```
since for this particular change I want to be modifying the .archive class and that has its own partial, I expect I needed to copy over the whole _sass/ directory. Here is a screenshot of my vscode project explorer, to show what I have done to structure the directories within my project: 

image

  So I'm doing this now. in the _sass/_archive.scss partial, I have added that padding line:

```css
.archive {
  margin-top: 1em;
  margin-bottom: 2em;
  padding 0 3rem !important;

  @include breakpoint($large) {
    float: right;
    width: calc(100% - #{$right-sidebar-width-narrow});
    padding-right: $right-sidebar-width-narrow;
  }

  @include breakpoint($x-large) {
    width: calc(100% - #{$right-sidebar-width});
    padding-right: $right-sidebar-width;
  }
}
```

but when I am doing `localdev` I am not seeing this style show up when I inspect the page with chrome dev tools.

### PR DESCRIPTION
**Pull request by SeanKilleen**
Looking into it, because why not. No idea if I'll succeed yet.

Resolves https://github.com/excellalabs/blog-in-a-box/issues/90, hopefully.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
Ahh, I missed this gem in the docs for minimal mistakes:

> Note: To make more extensive changes and customize the Sass partials bundled in the gem. You will need to copy the complete contents of the _sass directory to <your_project> due to the way Jekyll currently reads those files.

Given that, the best course of action is going to be to pull down main.scss, add a custom.scss that you reference from main, and add your updates there I think.

**Comment by SeanKilleen** [comment]
@nsubordin81 I figured it out. 

Minimal mistakes is assuming you're operating from the root of the repository. But one trade-off we had to make for GitHub pages is that everything in blog-in-the-box is in the `docs` subfolder.

So, your overrides weren't overriding because the file wasn't in the right spot.

I simplified the SASS change too (I think). Let me know if you've got more questions!

**Review by nsubordin81 — APPROVED** [review]

**Comment by SeanKilleen** [comment]
@nsubordin81 looks like the markdown linter and spell-checker caught some errors for your other article. Want me to punch those up while I'm here in this PR?

**Comment by nsubordin81** [comment]
oh, shoot sorry I missed your message before merging. I was looking over those, the only one I could find was the bareURL issue, for the spellchecker I had trouble finding the output, it looked like the config was out of date? 

I'll take it as an exercise to clean them up, if I can figure out what the issue is for the spell checker

**Pull request merged**
